os: linux

language: ruby

services:
  - docker

before_install:
  - docker build -t wahidthomasalmasih/docker-react -f Dockerfile.dev .

script:
  - docker run wahidthomasalmasih/docker-react npm run test -- --coverage